version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ecommerce-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    networks:
      - ecommerce-network

  frontend-user:
    build:
      context: ./frontend/user
      target: dev
    container_name: ecommerce-frontend-user
    env_file:
      - ./frontend/user/.env.development
    ports:
      - 8001:8000
    networks:
      - ecommerce-network
    depends_on:
      - backend

  frontend-admin:
    build:
      context: ./frontend/admin
      target: dev
    container_name: ecommerce-frontend-admin
    env_file:
      - ./frontend/admin/.env.development
    ports:
      - 8000:8000
    networks:
      - ecommerce-network
    depends_on:
      - backend
      

  
networks:
  ecommerce-network:
    driver: bridge