version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ecommerce-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    networks:
      - ecommerce-network
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  frontend-user:
    build:
      context: ./frontend/user
      target: dev
    container_name: ecommerce-frontend-user
    env_file:
      - ./frontend/user/.env.development
    ports:
      - 8001:8000
    develop:
      watch:
        - action: sync
          path: ./frontend/user
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    networks:
      - ecommerce-network
    depends_on:
      - backend

  frontend-admin:
    build:
      context: ./frontend/admin
      target: dev
    container_name: ecommerce-frontend-admin
    env_file:
      - ./frontend/admin/.env.development
    ports:
      - 8000:8000
    networks:
      - ecommerce-network
    develop:
     watch:
        - action: sync
          path: ./frontend/admin
          target: /app/

        - action: rebuild
          path: ./frontend/admin/package.json
    depends_on:
      - backend
      

  
networks:
  ecommerce-network:
    driver: bridge