version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ecommerce-backend
    image: jitheshmjithooz/ecommerce:backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - ecommerce-network

  frontend-user:
    build:
      context: ./frontend/user
      target: prod
    image: jitheshmjithooz/ecommerce:frontend-user
    container_name: ecommerce-frontend-user
    restart: unless-stopped
    env_file:
      - ./frontend/user/.env.production
    ports:
      - "8000:80"
    networks:
      - ecommerce-network
    depends_on:
      - backend

  frontend-admin:
    build:
      context: ./frontend/admin
      target: prod
    image: jitheshmjithooz/ecommerce:frontend-admin
    container_name: ecommerce-frontend-admin
    restart: unless-stopped
    env_file:
      - ./frontend/admin/.env.production
    ports:
      - "8001:80"

    networks:
      - ecommerce-network
    depends_on:
      - backend

networks:
  ecommerce-network:
    driver: bridge
