apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admins-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: ecommerce-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-user
spec:
  selector:
    app: frontend-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: frontend-admin
spec:
  selector:
    app: frontend-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
   
